In [1]:
from scipy.stats import norm
import numpy as np
import pandas as pd
import yfinance as yf

In [15]:
data=pd.DataFrame()
data= yf.download('^NSEI', start='2025-10-1')['Close']
data

/var/folders/5b/1yvmvb2x2f753vb6qj5q9w000000gn/T/ipykernel_4699/345902500.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data= yf.download('^NSEI', start='2025-10-1')['Close']
[*********************100%***********************]  1 of 1 completed

Ticker             ^NSEI
Date
2025-10-01  24836.300781
2025-10-03  24894.250000
2025-10-06  25077.650391
2025-10-07  25108.300781
2025-10-08  25046.150391
2025-10-09  25181.800781
2025-10-10  25285.349609
2025-10-13  25227.349609
2025-10-14  25145.500000
2025-10-15  25323.550781
2025-10-16  25585.300781
2025-10-17  25709.849609
2025-10-20  25843.150391
2025-10-21  25868.599609
2025-10-23  25891.400391
2025-10-24  25795.150391
2025-10-27  25966.050781
2025-10-28  25936.199219
2025-10-29  26053.900391
2025-10-30  25877.849609
2025-10-31  25722.099609
2025-11-03  25763.349609
2025-11-04  25597.650391
2025-11-06  25509.699219
2025-11-07  25492.300781
2025-11-10  25574.349609
2025-11-11  25694.949219
2025-11-12  25875.800781
2025-11-13  25879.150391
2025-11-14  25910.050781
2025-11-17  26013.449219
2025-11-18  25910.050781
2025-11-19  26052.650391
2025-11-20  26192.150391
2025-11-21  26068.150391
2025-11-24  25959.500000
2025-11-25  25884.800781
2025-11-26  26205.300781
2025-11-27  26215.550781
2025-11-28  26202.949219

In [16]:
log_returns= np.log(1+ data.pct_change())
log_returns

Ticker         ^NSEI
Date
2025-10-01       NaN
2025-10-03  0.002331
2025-10-06  0.007340
2025-10-07  0.001221
2025-10-08 -0.002478
2025-10-09  0.005401
2025-10-10  0.004104
2025-10-13 -0.002296
2025-10-14 -0.003250
2025-10-15  0.007056
2025-10-16  0.010283
2025-10-17  0.004856
2025-10-20  0.005171
2025-10-21  0.000984
2025-10-23  0.000881
2025-10-24 -0.003724
2025-10-27  0.006603
2025-10-28 -0.001150
2025-10-29  0.004528
2025-10-30 -0.006780
2025-10-31 -0.006037
2025-11-03  0.001602
2025-11-04 -0.006452
2025-11-06 -0.003442
2025-11-07 -0.000682
2025-11-10  0.003213
2025-11-11  0.004705
2025-11-12  0.007014
2025-11-13  0.000129
2025-11-14  0.001193
2025-11-17  0.003983
2025-11-18 -0.003983
2025-11-19  0.005489
2025-11-20  0.005340
2025-11-21 -0.004745
2025-11-24 -0.004177
2025-11-25 -0.002882
2025-11-26  0.012306
2025-11-27  0.000391
2025-11-28 -0.000481

In [17]:
stdev= log_returns.std()*250**0.5
stdev

Ticker
^NSEI    0.074982
dtype: float64

In [18]:
def d1(s,k,r,t,stdev):
    return (np.log(s/k) + (r+ stdev**2*0.5)*t)/(stdev*(t**0.5))

In [19]:
def d2(s,k,r,t,stdev):
    return (np.log(s/k) + (r- stdev**2*0.5)*t)/(stdev*(t**0.5))

In [20]:
def BSM(s,k,r,t,stdev):
    return (s*norm.cdf(d1(s,k,r,t,stdev))) - (k*np.exp(-r*t)*norm.cdf(d2(s,k,r,t,stdev)))

In [21]:
s=data.iloc[-1]
s

Ticker
^NSEI    26202.949219
Name: 2025-11-28 00:00:00, dtype: float64

In [22]:
k= 26200
r= 0.065
t=(30/365)

In [23]:
d1(s,k,r,t,stdev)

Ticker
^NSEI    0.264509
dtype: float64

In [24]:
d2(s,k,r,t,stdev)

Ticker
^NSEI    0.243013
dtype: float64

In [25]:
d1(s,k,r,t,stdev) - stdev*np.sqrt(t)

Ticker
^NSEI    0.243013
dtype: float64

In [26]:
BSM(s,k,r,t,stdev)

Ticker
^NSEI    302.550296
Name: 2025-11-28 00:00:00, dtype: float64